#!/bin/bash

MSG=$1
cd $PWD

if [ "$MSG" == "" ]; then
  echo "... Error: empty commit message"
else
  BRANCH=$(git rev-parse --abbrev-ref HEAD)

  git add -A
  git commit -m "$MSG"
  git push origin $BRANCH
fi