#!/bin/bash

SCRIPTSRC=`readlink -f "$0" || echo "$0"`
RUN_PATH=`dirname "${SCRIPTSRC}" || echo .`

source ${RUN_PATH}/_git_def.sh

cd $PWD
BRANCH=$1

if [ "${BRANCH}" == "" ]; then
  echo "... Error: empty branch"
else
  if [ "$2" == "-d" ]; then
    if [ -f "${BRANCH_DEV_FILE}" ]; then
      BRANCH_DEV=$(cat "${BRANCH_DEV_FILE}")
    else
      BRANCH_DEV='develop'
    fi
  
    git checkout ${BRANCH_DEV}
    exit_on_error $? !!
    git pull origin ${BRANCH_DEV}
    exit_on_error $? !!
  fi
  git checkout -b ${BRANCH}
fi
