#!/bin/bash

SCRIPTSRC=`readlink -f "$0" || echo "$0"`
RUN_PATH=`dirname "${SCRIPTSRC}" || echo .`

source ${RUN_PATH}/_git_def.sh

BRANCH=$1
cd $PWD

if [ "$BRANCH" == "" ]; then
  echo "... Error: empty branch"
else
  git fetch origin
  echo "--------------------------------------------------------"
  echo -e $BS"Result:"$BE
  git branch --all | grep "$BRANCH"
  echo "--------------------------------------------------------"
fi