#!/bin/bash

SCRIPTSRC=`readlink -f "$0" || echo "$0"`
RUN_PATH=`dirname "${SCRIPTSRC}" || echo .`

source ${RUN_PATH}/_git_def.sh

cd $PWD

if [[ "$1" == "" ]]; then
  BRANCH=$(git rev-parse --abbrev-ref HEAD)
else
  BRANCH="$1"
fi

if [[ "${BRANCH}" == "" ]]; then
  echo "... Error: empty branch"
else  
  echo "--------------------------------------------------------"
  echo -e $BS"Run command: push origin "${BRANCH}$BE
  echo "--------------------------------------------------------"
  git push origin ${BRANCH}
fi
