#!/bin/bash

SCRIPTSRC=`readlink -f "$0" || echo "$0"`
RUN_PATH=`dirname "${SCRIPTSRC}" || echo .`

source ${RUN_PATH}/_git_def.sh

cd $PWD
MSG=$1

if [ "${MSG}" == "" ]; then
  echo "... Error: empty commit message"
else
  AMEND=''
  if [[ "$2" == "-a" ]]; then
    AMEND='--amend'
  fi

  git add -A
  git commit -m "${MSG}" ${AMEND}
  exit_on_error $? !!

  if [[ "$2" == "-p" ]]; then
    git-pull
    exit_on_error $? !!
    git-push
  fi
fi
