#!/bin/bash

SCRIPTSRC=`readlink -f "$0" || echo "$0"`
RUN_PATH=`dirname "${SCRIPTSRC}" || echo .`

source ${RUN_PATH}/_git_def.sh

BRANCH=$(git rev-parse --abbrev-ref HEAD)
cd $PWD

if [ -f './.git/branch_dev' ]; then
  BRANCH_DEV=$(cat './.git/branch_dev')
else
  BRANCH_DEV='dev'
fi

if [ "$BRANCH" == "" ]; then
  echo "... Error: empty branch"
else
  if [ "$BRANCH" == "$BRANCH_DEV" ]; then
    echo "... Error:  you are already in dev branch '$BRANCH_DEV'"
  else  
    echo ""
    echo -e $BS">> Current branch '"$BRANCH"' <<"$BE
    echo ""
    
    echo "--------------------------------------------------------"
    echo -e $BS"Run command: checkout "$BRANCH_DEV$BE
    echo "--------------------------------------------------------"
    git checkout $BRANCH_DEV
    exit_on_error $? !!
    echo "--------------------------------------------------------"
    echo -e $BS"Run command: fetch origin (get branch list)"$BE
    echo "--------------------------------------------------------"
    git fetch origin
    echo "--------------------------------------------------------"
    echo -e $BS"Run command: pull origin $BRANCH_DEV (update $BRANCH_DEV)"$BE
    echo "--------------------------------------------------------"
    git pull --no-commit origin $BRANCH_DEV
    exit_on_error $? !!
    git add -A
    git commit -m "Merge branch '$BRANCH_DEV'"
    echo "--------------------------------------------------------"
    echo -e $BS"Run command: checkout "$BRANCH$BE
    echo "--------------------------------------------------------"
    git checkout $BRANCH
    exit_on_error $? !!
    echo "--------------------------------------------------------"
    echo -e $BS"Run command: pull origin "$BRANCH" (update "$BRANCH")"$BE
    echo "--------------------------------------------------------"
    git pull --no-commit origin $BRANCH
    exit_on_error $? !!
    git add -A
    git commit -m "Merge branch '"$BRANCH"'"
    echo "--------------------------------------------------------"
    echo -e $BS"Run command: pull origin $BRANCH_DEV (merge $BRANCH_DEV to "$BRANCH")"$BE
    echo "--------------------------------------------------------"
    git pull --no-commit origin $BRANCH_DEV
    exit_on_error $? !!
    git add -A
    git commit -m "Merge branch '$BRANCH_DEV' to '"$BRANCH"'"
    echo "--------------------------------------------------------"
    echo -e $BS"Run command: push origin "$BRANCH$BE
    echo "--------------------------------------------------------"
    git push origin $BRANCH
    exit_on_error $? !!
    echo "--------------------------------------------------------"
    echo -e $BS"Run command: checkout $BRANCH_DEV"$BE
    echo "--------------------------------------------------------"
    git checkout $BRANCH_DEV
    exit_on_error $? !!
    echo "--------------------------------------------------------"
    echo -e $BS"Run command: pull origin "$BRANCH" (merge "$BRANCH" to $BRANCH_DEV)"$BE
    echo "--------------------------------------------------------"
    git pull --no-commit origin $BRANCH
    exit_on_error $? !!
    git add -A
    git commit -m "Merge branch '"$BRANCH"' to '$BRANCH_DEV'"
    echo "--------------------------------------------------------"
    echo -e $BS"Run command: push origin $BRANCH_DEV"$BE
    echo "--------------------------------------------------------"
    git push origin $BRANCH_DEV
  fi
fi
