#!/bin/bash

SCRIPTSRC=`readlink -f "$0" || echo "$0"`
RUN_PATH=`dirname "${SCRIPTSRC}" || echo .`

source ${RUN_PATH}/_git_def.sh

MAIN='dev'
BRANCH=$1
cd $PWD

if [ "$BRANCH" == "" ]; then
  echo "... Error: empty branch"
else
  git checkout $MAIN
  exit_on_error $? !!
  git pull origin $MAIN
  exit_on_error $? !!
  git checkout -b $BRANCH
  exit_on_error $? !!
  git push origin $BRANCH
fi