#!/bin/bash

SCRIPTSRC=`readlink -f "$0" || echo "$0"`
RUN_PATH=`dirname "${SCRIPTSRC}" || echo .`

source ${RUN_PATH}/_git_flow_cmd.sh
source ${RUN_PATH}/_git_def.sh

git-checkout master
exit_on_error $? !!

git_flow_cmd_init 'hotfix' 'start' "$1"
