#!/bin/bash

SCRIPTSRC=`readlink -f "$0" || echo "$0"`
RUN_PATH=`dirname "${SCRIPTSRC}" || echo .`

source ${RUN_PATH}/_git_def.sh

BRANCH=$(git rev-parse --abbrev-ref HEAD)
cd $PWD

if [ "$BRANCH" == "" ]; then
  echo "... Error: empty branch"
else
  if [ "$BRANCH" == "dev" ]; then
    echo "... Error: current branch is 'dev'"
  else  
    echo ""
    echo -e $BS">> Current branch '"$BRANCH"' <<"$BE
    echo ""
    
    echo "--------------------------------------------------------"
    echo -e $BS"Run command: checkout dev"$BE
    echo "--------------------------------------------------------"
    git checkout dev
    exit_on_error $? !!
    echo "--------------------------------------------------------"
    echo -e $BS"Run command: fetch origin (get branch list)"$BE
    echo "--------------------------------------------------------"
    git fetch origin
    echo "--------------------------------------------------------"
    echo -e $BS"Run command: pull origin dev (update dev)"$BE
    echo "--------------------------------------------------------"
    git pull --no-commit origin dev
    exit_on_error $? !!
    git add -A
    git commit -m "Marge branch 'dev'"
    echo "--------------------------------------------------------"
    echo -e $BS"Run command: checkout "$BRANCH$BE
    echo "--------------------------------------------------------"
    git checkout $BRANCH
    exit_on_error $? !!
    echo "--------------------------------------------------------"
    echo -e $BS"Run command: pull origin "$BRANCH" (update "$BRANCH")"$BE
    echo "--------------------------------------------------------"
    git pull --no-commit origin $BRANCH
    exit_on_error $? !!
    git add -A
    git commit -m "Marge branch '"$BRANCH"'"
    echo "--------------------------------------------------------"
    echo -e $BS"Run command: pull origin dev (merge dev to "$BRANCH")"$BE
    echo "--------------------------------------------------------"
    git pull --no-commit origin dev
    exit_on_error $? !!
    git add -A
    git commit -m "Marge branch 'dev' to '"$BRANCH"'"
    echo "--------------------------------------------------------"
    echo -e $BS"Run command: push origin "$BRANCH$BE
    echo "--------------------------------------------------------"
    git push origin $BRANCH
    exit_on_error $? !!
    echo "--------------------------------------------------------"
    echo -e $BS"Run command: checkout dev"$BE
    echo "--------------------------------------------------------"
    git checkout dev
    exit_on_error $? !!
    echo "--------------------------------------------------------"
    echo -e $BS"Run command: pull origin "$BRANCH" (merge "$BRANCH" to dev)"$BE
    echo "--------------------------------------------------------"
    git pull --no-commit origin $BRANCH
    exit_on_error $? !!
    git add -A
    git commit -m "Marge branch '"$BRANCH"' to 'dev'"
    echo "--------------------------------------------------------"
    echo -e $BS"Run command: push origin dev"$BE
    echo "--------------------------------------------------------"
    git push origin dev
  fi
fi
