#!/bin/bash

SCRIPTSRC=`readlink -f "$0" || echo "$0"`
RUN_PATH=`dirname "${SCRIPTSRC}" || echo .`

source ${RUN_PATH}/_git_flow_cmd.sh
source ${RUN_PATH}/_git_def.sh

MSG=$1
NAME=$(git_flow_get_name 'hotfix')

if [[ "${MSG}" != "" ]]; then
    git add -A
    git commit -m "${NAME} ${MSG}"
    exit_on_error $? !!
fi

git_flow_cmd_init 'hotfix' 'finish' "${NAME}" -m "Tagging hotfix ${NAME}"
exit_on_error $? !!

git-pull
exit_on_error $? !!

git-push
exit_on_error $? !!

git-checkout master
exit_on_error $? !!

git-push
exit_on_error $? !!

git-push "${NAME}"
