#!/bin/bash

SCRIPTSRC=`readlink -f "$0" || echo "$0"`
RUN_PATH=`dirname "${SCRIPTSRC}" || echo .`

source ${RUN_PATH}/_git_def.sh

cd $PWD
MSG=$1

if [ "$MSG" == "" ]; then
  echo "... Error: empty commit message"
else
  BRANCH=$(git rev-parse --abbrev-ref HEAD)

  git add -A
  git commit -m "$MSG"
  git push origin $BRANCH
fi