#!/bin/bash

SCRIPTSRC=`readlink -f "$0" || echo "$0"`
RUN_PATH=`dirname "${SCRIPTSRC}" || echo .`

source ${RUN_PATH}/_git_flow_cmd.sh

MSG=$1

if [ "${MSG}" == "" ]; then
    echo "Error: empty commit message"
    echo ""
    echo "  Usage: git-flow-bugfix-publish 'commit message'"
    echo ""
else
    NAME=$(git_flow_get_name 'bugfix')

    git add -A
    git commit -m "${MSG}"
    git_flow_cmd_init 'bugfix' 'publish' "${NAME}"
fi
