#!/bin/bash

SCRIPTSRC=`readlink -f "$0" || echo "$0"`
RUN_PATH=`dirname "${SCRIPTSRC}" || echo .`

source ${RUN_PATH}/_git_def.sh

cd $PWD

if [ -f "${BRANCH_DEV_FILE}" ]; then
  BRANCH=$(cat "${BRANCH_DEV_FILE}")
else
  BRANCH='develop'
fi

if [ "${BRANCH}" == "" ]; then
  echo "... Error: empty branch"
else
  git fetch origin
  EXISTS=$(git branch -a | egrep "${BRANCH}$")
  
  if [ "${EXISTS}" == "" ]; then
    echo "... Error: undefined branch ${BRANCH}"
  else
    git checkout ${BRANCH}
    exit_on_error $? !!
    git pull --rebase origin ${BRANCH}
  fi
fi
