#!/bin/bash

SCRIPTSRC=`readlink -f "$0" || echo "$0"`
RUN_PATH=`dirname "${SCRIPTSRC}" || echo .`

source ${RUN_PATH}/_git_def.sh

cd $PWD
BRANCH_CURRENT=$(git rev-parse --abbrev-ref HEAD)

if [ -f "${BRANCH_DEV_FILE}" ]; then
  BRANCH_DEV=$(cat "${BRANCH_DEV_FILE}")
else
  BRANCH_DEV='develop'
fi

if [ "${BRANCH_CURRENT}" == "" ]; then
  echo "... Error: empty branch"
else
  if [ "${BRANCH_CURRENT}" == "${BRANCH_DEV}" ]; then
    echo "... Error: you are already in dev branch '${BRANCH_DEV}'"
  else  
    echo "--------------------------------------------------------"
    echo -e $BS"Run command: pull origin "${BRANCH_CURRENT}" (update "${BRANCH_CURRENT}")"$BE
    echo "--------------------------------------------------------"
    git pull --rebase origin ${BRANCH_CURRENT}
    exit_on_error $? !!
    echo "--------------------------------------------------------"
    echo -e $BS"Run command: pull origin ${BRANCH_DEV} (merge ${BRANCH_DEV} to "${BRANCH_CURRENT}")"$BE
    echo "--------------------------------------------------------"
    git pull --rebase origin ${BRANCH_DEV}
  fi
fi
