#!/bin/bash

SCRIPTSRC=`readlink -f "$0" || echo "$0"`
RUN_PATH=`dirname "${SCRIPTSRC}" || echo .`

source ${RUN_PATH}/_git_def.sh

DIR="$PWD"
cd ${DIR}

BRANCH_CURRENT=$(git rev-parse --abbrev-ref HEAD)

if [[ "${BRANCH_CURRENT}" == "" ]]; then
  echo "... Error: empty branch"
else
  echo "--------------------------------------------------------"
  echo -e $BS"Run command: pull origin "${BRANCH_CURRENT}" (update "${BRANCH_CURRENT}")"$BE
  echo "--------------------------------------------------------"
  git pull --rebase origin ${BRANCH_CURRENT}
  exit_on_error $? !!
  
  if [[ "$1" != "" ]]; then
    BRANCH_PULL=$1
    
    echo "--------------------------------------------------------"
    echo -e $BS"Run command: pull origin ${BRANCH_PULL} (merge ${BRANCH_PULL} to "${BRANCH_CURRENT}")"$BE
    echo "--------------------------------------------------------"
    git pull --rebase origin ${BRANCH_PULL}
    exit_on_error $? !!
  fi
fi
