#!/bin/bash

SCRIPTSRC=`readlink -f "$0" || echo "$0"`
RUN_PATH=`dirname "${SCRIPTSRC}" || echo .`

source ${RUN_PATH}/_git_def.sh

TAG=$1
MSG=$2
cd $PWD

if [ "$TAG" == "" ]; then
  echo "... Error: empty tag name"
else
  if [ "$MSG" == "" ]; then 
    git tag $TAG
  else
    git tag -a $TAG -m "$MSG"
  fi
  exit_on_error $? !!
  git push origin $TAG
fi